apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test1
  namespace: assets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: test1
  serviceName: test1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: test1
    spec:
      containers:
        - image: centos
          name: test1
          volumeMounts:
            - mountPath: /data
              name: persistent-storage
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: ebs-claim